name: populate_or_update_cache

# Cached on main, should be available on every branch derived from main
on:
  push:
    branches:
      - "main"

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # key: $${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # My understanding: hashFiles will include any Cargo.lock file in the checked
      # out working directory. If a PR includes a Cargo.lock (which it should not)
      # then that will be included in the hashFiles call.
      # Since the hash is not needed, as Cargo.lock will be updated rarely & manually
      # anyway, a simpler key works and can prevent potential bad things
      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo
        key: ${{ runner.os }}-cargo-stylua-cache

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install stylua
        run: |
          cargo install stylua
